services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: pinpoint
      POSTGRES_USER: pinpoint
      POSTGRES_PASSWORD: pinpoint
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
